name: TruffleHog Full History Scan (onboarding)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  trufflehog-full-history:
    name: trufflehog-full-history
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: TruffleHog OSS (full history)
        uses: trufflesecurity/trufflehog@88524578ce32e1a8521c29dd38af9d9200ff92cc
        with:
          extra_args: --results=verified,unknown
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
